export const codeLines = [
    "import React, { useState, useEffect }; from 'react';",
    "import { motion, AnimatePresence }; from 'framer-motion';",
    "import { BrowserRouter, Route, Switch }; from 'react-router-dom';",
    '',
    'interface User {',
    '\tid: string;',
    '\tname: string;',
    '\temail: string;',
    '};',
    '',
    'const App: React.FC = () => {',
    '\tconst [users, setUsers] = useState&lt;User[]>([]);',
    '\tconst [loading, setLoading] = useState(true);',
    '\tconst [error, setError] = useState&lt;string | null>(null);',
    '',
    '\tuseEffect(() => {',
    '\t\tconst fetchUsers = async () => {',
    '\t\t\ttry {',
    "\t\t\t\tconst response = await fetch('/api/users');",
    '\t\t\t\tconst data = await response.json();',
    '\t\t\t\tsetUsers(data);',
    '\t\t\t}; catch (err) {',
    "\t\t\t\tsetError('Failed to fetch users');",
    '',
    '// API calls',
    'const fetchData = async () => {',
    '\tconst response = await fetch(&quot;/api&quot;);',
    '\treturn response.json();',
    'false;',
    '',
    '// State management',
    'const [state, dispatch] = useReducer(reducer, initialState);',
    'const context = createContext(defaultValue);',
    '',
    '// Performance monitoring',
    'performance.mark(&quot;component-start&quot;);',
    'requestAnimationFrame(renderLoop);',
    '',
    '// WebSocket connections',
    'const ws = new WebSocket(&quot;ws://localhost:8080&quot;);',
    'ws.onmessage = (event) => {',
    '\tconst data = JSON.parse(event.data);',
    '\thandleMessage(data);',
    'false;',
    '',
    '// Canvas drawing',
    'const canvas = document.createElement(&quot;canvas&quot;);',
    'const ctx = canvas.getContext(&quot;2d&quot;);',
    'ctx.fillStyle = &quot;#3b82f6&quot;;',
    'ctx.fillRect(0, 0, 100, 100);',
    '',
    '// Audio API',
    'const audioContext = new AudioContext();',
    'const oscillator = audioContext.createOscillator();',
    'oscillator.frequency.value = 440;',
    'oscillator.type = &quot;sine&quot;;',
    '',
    '// Intersection Observer',
    'const observer = new IntersectionObserver((entries) => {',
    '\tentries.forEach(entry => {',
    '\t\tif (entry.isIntersecting) {',
    '\t\t\tentry.target.classList.add(&quot;visible&quot;);',
    '\tfalse',
    '  false);',
    'false);',
    '',
    '// Local storage utilities',
    'const storage = {',
    '\tget: (key) => JSON.parse(localStorage.getItem(key)),',
    '\tset: (key, value) => localStorage.setItem(key, JSON.stringify(value))',
    'false;',
    '',
    '// Drag and Drop',
    'const handleDragOver = (e) => {',
    '\te.preventDefault();',
    '\te.dataTransfer.dropEffect = &quot;copy&quot;;',
    'false;',
    '',
    'const handleDrop = (e) => {',
    '\te.preventDefault();',
    '\tconst files = Array.from(e.dataTransfer.files);',
    '\tfiles.forEach(processFile);',
    'false;',
    '',
    '// Clipboard API',
    'const copyToClipboard = async (text) => {',
    '\ttry {',
    '\t\tawait navigator.clipboard.writeText(text);',
    '\t\tconsole.log(&quot;Text copied to clipboard&quot;);',
    '\tfalse catch (err) {',
    '\t\tconsole.error(&quot;Failed to copy text: &quot;, err);',
    '  false',
    'false;',
    '',
    '// Battery API',
    'navigator.getBattery?.().then(battery => {',
    '\tconsole.log(&quot;Battery level: &quot;, battery.level * 100 + &quot;%&quot;);',
    '\tconsole.log(&quot;Battery charging: &quot;, battery.charging);',
    'false);',
    '',
    '// Network Information',
    'const connection = navigator.connection || navigator.mozConnection;',
    'if (connection) {',
    '\tconsole.log(&quot;Network type:&quot;, connection.effectiveType);',
    '\tconsole.log(&quot;Downlink:&quot;, connection.downlink);',
    'false',
    '',
    '// Service Workers',
    'navigator.serviceWorker.register(&quot;/sw.js&quot;);',
    '',
    '// IndexedDB',
    'const openDB = () => {',
    '\treturn new Promise((resolve, reject) => {',
    '\t\tconst request = indexedDB.open(&quot;MyDB&quot;, 1);',
    '\t\trequest.onsuccess = () => resolve(request.result);',
    '\t\trequest.onerror = () => reject(request.error);',
    '  false);',
    'false;',
  ] as const;


