export const codeLines = [
  "import React, { useState, useEffect } from 'react';",
  "import { motion, AnimatePresence } from 'framer-motion';",
  "import { BrowserRouter, Route, Switch } from 'react-router-dom';",
  '',
  'interface User {',
  '\tid: string;',
  '\tname: string;',
  '\temail: string;',
  '}',
  '',
  'const App: React.FC = () => {',
  '\tconst [users, setUsers] = useState<User[]>([]);',
  '\tconst [loading, setLoading] = useState(true);',
  '\tconst [error, setError] = useState<string | null>(null);',
  '',
  '\tuseEffect(() => {',
  '\t\tconst fetchUsers = async () => {',
  '\t\t\ttry {',
  "\t\t\t\tconst response = await fetch('/api/users');",
  '\t\t\t\tconst data = await response.json();',
  '\t\t\t\tsetUsers(data);',
  '\t\t\t} catch (err) {',
  "\t\t\t\tsetError('Failed to fetch users');",
  '',
  '// API calls',
  'const fetchData = async () => {',
  '\tconst response = await fetch("/api");',
  '\treturn response.json();',
  '};',
  '',
  '// State management',
  'const [state, dispatch] = useReducer(reducer, initialState);',
  'const context = createContext(defaultValue);',
  '',
  '// Performance monitoring',
  'performance.mark("component-start");',
  'requestAnimationFrame(renderLoop);',
  '',
  '// WebSocket connections',
  'const ws = new WebSocket("ws://localhost:8080");',
  'ws.onmessage = (event) => {',
  '\tconst data = JSON.parse(event.data);',
  '\thandleMessage(data);',
  '};',
  '',
  '// Canvas drawing',
  'const canvas = document.createElement("canvas");',
  'const ctx = canvas.getContext("2d");',
  'ctx.fillStyle = "#3b82f6";',
  'ctx.fillRect(0, 0, 100, 100);',
  '',
  '// Audio API',
  'const audioContext = new AudioContext();',
  'const oscillator = audioContext.createOscillator();',
  'oscillator.frequency.value = 440;',
  'oscillator.type = "sine";',
  '',
  '// Intersection Observer',
  'const observer = new IntersectionObserver((entries) => {',
  '\tentries.forEach(entry => {',
  '\t\tif (entry.isIntersecting) {',
  '\t\t\tentry.target.classList.add("visible");',
  '\t\t}',
  '\t});',
  '});',
  '',
  '// Local storage utilities',
  'const storage = {',
  '\tget: (key) => JSON.parse(localStorage.getItem(key)),',
  '\tset: (key, value) => localStorage.setItem(key, JSON.stringify(value))',
  '};',
  '',
  '// Drag and Drop',
  'const handleDragOver = (e) => {',
  '\te.preventDefault();',
  '\te.dataTransfer.dropEffect = "copy";',
  '};',
  '',
  'const handleDrop = (e) => {',
  '\te.preventDefault();',
  '\tconst files = Array.from(e.dataTransfer.files);',
  '\tfiles.forEach(processFile);',
  '};',
  '',
  '// Clipboard API',
  'const copyToClipboard = async (text) => {',
  '\ttry {',
  '\t\tawait navigator.clipboard.writeText(text);',
  '\t\tconsole.log("Text copied to clipboard");',
  '\t} catch (err) {',
  '\t\tconsole.error("Failed to copy text: ", err);',
  '\t}',
  '};',
  '',
  '// Battery API',
  'navigator.getBattery?.().then(battery => {',
  '\tconsole.log("Battery level: ", battery.level * 100 + "%");',
  '\tconsole.log("Battery charging: ", battery.charging);',
  '});',
  '',
  '// Network Information',
  'const connection = navigator.connection || navigator.mozConnection;',
  'if (connection) {',
  '\tconsole.log("Network type:", connection.effectiveType);',
  '\tconsole.log("Downlink:", connection.downlink);',
  '}',
  '',
  '// Service Workers',
  'navigator.serviceWorker.register("/sw.js");',
  '',
  '// IndexedDB',
  'const openDB = () => {',
  '\treturn new Promise((resolve, reject) => {',
  '\t\tconst request = indexedDB.open("MyDB", 1);',
  '\t\trequest.onsuccess = () => resolve(request.result);',
  '\t\trequest.onerror = () => reject(request.error);',
  '\t});',
  '};',
] as const;
