export const SPARK_CONFIG = {
  MAX_SPARKS: 15,
  MIN_SPEED_FOR_SPARK: 100,
  SPARK_CHANCE: 0.7,
  LIFE_DECAY: 0.02,
  PHYSICS_STEP: 0.016,
  MIN_SPARK_SPEED: 50,
  MAX_SPARK_SPEED: 150,
} as const;

